name: Renovate Auto-Merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Approve and auto-merge PR
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL" \
            --delete-branch
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
